/**
 * Synthetic demo household — Phase 2.
 *
 * ONE hand-authored, clearly-labeled demo household: a realistic U.S.
 * mid-month paycheck household. Deterministic by construction — no Date.now(),
 * no Math.random(); every timestamp and amount is a constant and the snapshot
 * is deep-frozen, so `createDemoSnapshot()` always returns identical data.
 *
 * Everything here is labeled `source: "demo"` and must never be presented as
 * real accounts, balances, transactions, or payment successes.
 */
import type {
  Account,
  AutomationRule,
  Debt,
  GivingPlan,
  Goal,
  GoalContribution,
  Obligation,
  Paycheck,
  Transaction,
} from "./types";

/** Shown wherever demo data appears in the UI. */
export const DEMO_LABEL = "Synthetic demo data — not real accounts, balances, or transactions.";
export const DEMO_HOUSEHOLD = "Demo household";
export const DEMO_SNAPSHOT_VERSION = "2026.09.1";
/** Fixed snapshot instant so the data is identical on every call. */
export const DEMO_GENERATED_AT = "2026-09-10T12:00:00Z";

const DEMO = "demo" as const;

export interface DemoSnapshot {
  label: string;
  household: string;
  version: string;
  generatedAt: string;
  accounts: Account[];
  transactions: Transaction[];
  paychecks: Paycheck[];
  obligations: Obligation[];
  debts: Debt[];
  goals: Goal[];
  /** Optional giving plan — fixed amount, NO preselected percentage. */
  givingPlan: GivingPlan;
  /** Deposit history for goals — CONFIRMED, dated contributions with evidence. */
  goalContributions: GoalContribution[];
  /** Automation rules are DRAFT data only; Milestone A never executes them. */
  automationRules: AutomationRule[];
}

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === "object") {
    for (const key of Object.keys(value)) {
      deepFreeze((value as Record<string, unknown>)[key]);
    }
    Object.freeze(value);
  }
  return value;
}

const accounts: Account[] = [
  {
    id: "acc-checking",
    name: "Everyday Checking",
    type: "checking",
    connectionStatus: "demo",
    source: DEMO,
    owner: DEMO_HOUSEHOLD,
    currency: "USD",
    currentBalanceCents: 184211,
    // Available already reflects the pending grocery charge of $42.17.
    availableBalanceCents: 179994,
    availableCreditCents: null,
    creditLimitCents: null,
    externalId: null,
    institution: "Demo Community Bank",
    openedAt: "2021-03-14",
    updatedAt: "2026-09-10T08:30:00Z",
  },
  {
    id: "acc-savings",
    name: "High-Yield Savings",
    type: "savings",
    connectionStatus: "demo",
    source: DEMO,
    owner: DEMO_HOUSEHOLD,
    currency: "USD",
    currentBalanceCents: 845000,
    availableBalanceCents: 845000,
    availableCreditCents: null,
    creditLimitCents: null,
    externalId: null,
    institution: "Demo Community Bank",
    openedAt: "2021-03-14",
    updatedAt: "2026-09-10T08:30:00Z",
  },
  {
    id: "acc-card",
    name: "Platinum Rewards Card (demo)",
    type: "creditCard",
    connectionStatus: "demo",
    source: DEMO,
    owner: DEMO_HOUSEHOLD,
    currency: "USD",
    currentBalanceCents: -328744,
    availableBalanceCents: null,
    availableCreditCents: 371256,
    creditLimitCents: 700000,
    externalId: null,
    institution: "Demo Rewards Bank",
    openedAt: "2022-07-01",
    updatedAt: "2026-09-10T08:30:00Z",
  },
  {
    id: "acc-auto",
    name: "Auto Loan — 2022 Demo Compact",
    type: "autoLoan",
    connectionStatus: "demo",
    source: DEMO,
    owner: DEMO_HOUSEHOLD,
    currency: "USD",
    currentBalanceCents: -1245080,
    availableBalanceCents: null,
    availableCreditCents: null,
    creditLimitCents: null,
    externalId: null,
    institution: "Demo Motors Finance",
    openedAt: "2022-07-01",
    updatedAt: "2026-09-10T08:30:00Z",
  },
  {
    id: "acc-fed-sloans",
    name: "Federal Student Loans (Direct)",
    type: "studentLoan",
    connectionStatus: "demo",
    source: DEMO,
    owner: DEMO_HOUSEHOLD,
    currency: "USD",
    currentBalanceCents: -2130000,
    availableBalanceCents: null,
    availableCreditCents: null,
    creditLimitCents: null,
    externalId: null,
    institution: "U.S. Dept. of Education (demo)",
    openedAt: "2019-08-20",
    updatedAt: "2026-09-10T08:30:00Z",
  },
  {
    id: "acc-priv-sloans",
    name: "Private Student Loan (Demo Lender)",
    type: "studentLoan",
    connectionStatus: "demo",
    source: DEMO,
    owner: DEMO_HOUSEHOLD,
    currency: "USD",
    currentBalanceCents: -1870000,
    availableBalanceCents: null,
    availableCreditCents: null,
    creditLimitCents: null,
    externalId: null,
    institution: "Demo Lender Student Finance",
    openedAt: "2020-01-10",
    updatedAt: "2026-09-10T08:30:00Z",
  },
  {
    id: "acc-401k",
    name: "401(k) — Demo Employer",
    type: "retirement",
    connectionStatus: "demo",
    source: DEMO,
    owner: DEMO_HOUSEHOLD,
    currency: "USD",
    currentBalanceCents: 3421090,
    availableBalanceCents: null,
    availableCreditCents: null,
    creditLimitCents: null,
    externalId: null,
    institution: "Demo Employer 401(k)",
    openedAt: "2020-06-01",
    updatedAt: "2026-09-10T08:30:00Z",
  },
  {
    id: "acc-brokerage",
    name: "Brokerage (demo)",
    type: "brokerage",
    connectionStatus: "demo",
    source: DEMO,
    owner: DEMO_HOUSEHOLD,
    currency: "USD",
    currentBalanceCents: 515000,
    availableBalanceCents: null,
    availableCreditCents: null,
    creditLimitCents: null,
    externalId: null,
    institution: "Demo Securities",
    openedAt: "2023-02-15",
    updatedAt: "2026-09-10T08:30:00Z",
  },
  // Medical bill — tracked as a debt AND as an account record so it appears
  // in Accounts and the All-your-money overview. Every debt must be
  // inspectable: the account record is its inspection point (Finding 10).
  {
    id: "acc-medical",
    name: "Medical Bill — Demo Clinic",
    type: "loan",
    connectionStatus: "demo",
    source: DEMO,
    owner: DEMO_HOUSEHOLD,
    currency: "USD",
    currentBalanceCents: -124000,
    availableBalanceCents: null,
    availableCreditCents: null,
    creditLimitCents: null,
    externalId: null,
    institution: "Demo Clinic Billing",
    openedAt: "2026-04-02",
    updatedAt: "2026-09-10T08:30:00Z",
  },
];

const paychecks: Paycheck[] = [
  {
    id: "pc-0826",
    date: "2026-08-26",
    employer: "Demo Manufacturer",
    grossCents: 288462,
    netCents: 215384,
    received: true,
    accountId: "acc-checking",
    source: DEMO,
  },
  {
    id: "pc-0910",
    date: "2026-09-10",
    employer: "Demo Manufacturer",
    grossCents: 288462,
    netCents: 215384,
    received: true,
    accountId: "acc-checking",
    source: DEMO,
  },
  {
    id: "pc-0925",
    date: "2026-09-25",
    employer: "Demo Manufacturer",
    grossCents: 288462,
    netCents: 215384,
    // Not received yet — must be shown as estimated/uncertain until it arrives.
    received: false,
    accountId: "acc-checking",
    source: DEMO,
  },
];

const obligations: Obligation[] = [
  {
    id: "ob-rent",
    name: "Rent — Demo Apartments",
    amountCents: 165000,
    cadence: "monthly",
    dueDay: 1,
    category: "housing",
    essential: true,
    alreadyReflected: false,
    accountId: "acc-checking",
    source: DEMO,
  },
  {
    id: "ob-electric",
    name: "Electric — Demo Utility",
    amountCents: 9840,
    cadence: "monthly",
    dueDay: 12,
    category: "utilities",
    essential: true,
    alreadyReflected: false,
    accountId: "acc-checking",
    source: DEMO,
  },
  {
    id: "ob-internet",
    name: "Internet — Demo Fiber",
    amountCents: 6999,
    cadence: "monthly",
    dueDay: 15,
    category: "utilities",
    essential: true,
    alreadyReflected: false,
    accountId: "acc-checking",
    source: DEMO,
  },
  {
    id: "ob-cell",
    name: "Mobile — 2 lines (demo)",
    amountCents: 11250,
    cadence: "monthly",
    dueDay: 8,
    category: "utilities",
    essential: true,
    alreadyReflected: false,
    accountId: "acc-checking",
    source: DEMO,
  },
  {
    id: "ob-auto-ins",
    name: "Auto insurance (demo)",
    amountCents: 11833,
    cadence: "monthly",
    dueDay: 17,
    category: "insurance",
    essential: true,
    alreadyReflected: false,
    accountId: "acc-checking",
    source: DEMO,
  },
  {
    id: "ob-streaming",
    name: "Streaming (demo)",
    amountCents: 1599,
    cadence: "monthly",
    dueDay: 11,
    category: "subscription",
    essential: false,
    alreadyReflected: false,
    accountId: "acc-checking",
    source: DEMO,
  },
  {
    id: "ob-music",
    name: "Music (demo)",
    amountCents: 1099,
    cadence: "monthly",
    dueDay: 18,
    category: "subscription",
    essential: false,
    alreadyReflected: false,
    accountId: "acc-checking",
    source: DEMO,
  },
  {
    id: "ob-gym",
    name: "Gym — Demo Fitness",
    amountCents: 4500,
    cadence: "monthly",
    dueDay: 20,
    category: "subscription",
    essential: false,
    alreadyReflected: false,
    accountId: "acc-checking",
    source: DEMO,
  },
];

const debts: Debt[] = [
  {
    id: "debt-card",
    name: "Platinum Rewards Card",
    category: "creditCard",
    balanceCents: 328744,
    accountId: "acc-card",
    aprBps: 2299,
    aprKind: "fixed",
    minPaymentCents: 9600,
    minPaymentIsEstimate: true,
    minPaymentDueDay: 22,
    source: DEMO,
    notes: "Statement minimum shown is an estimate (~1% of balance + interest); always verify on the actual statement.",
  },
  {
    id: "debt-auto",
    name: "Auto Loan — 2022 Demo Compact",
    category: "autoLoan",
    balanceCents: 1245080,
    accountId: "acc-auto",
    aprBps: 649,
    aprKind: "fixed",
    minPaymentCents: 31240,
    minPaymentIsEstimate: false,
    minPaymentDueDay: 5,
    source: DEMO,
  },
  {
    id: "debt-federal",
    name: "Federal Student Loans (Direct)",
    category: "studentLoan",
    balanceCents: 2130000,
    accountId: "acc-fed-sloans",
    aprBps: 505,
    aprKind: "fixed",
    minPaymentCents: 14500,
    minPaymentIsEstimate: false,
    minPaymentDueDay: 25,
    source: DEMO,
    notes: "Federal and private student loans are kept separate — they are different loans with different options.",
  },
  {
    id: "debt-private",
    name: "Private Student Loan (Demo Lender)",
    category: "studentLoan",
    balanceCents: 1870000,
    accountId: "acc-priv-sloans",
    aprBps: 924,
    aprKind: "variable",
    minPaymentCents: 23200,
    minPaymentIsEstimate: false,
    minPaymentDueDay: 28,
    source: DEMO,
    notes: "Variable rate — any projection uses today's rate as an estimate.",
  },
  {
    id: "debt-medical",
    name: "Medical Bill — Demo Clinic",
    category: "medical",
    balanceCents: 124000,
    // The debt's inspection point: the account record it maps to. Keeps the
    // Medical Bill in Accounts and the All-your-money overview (Finding 10).
    accountId: "acc-medical",
    // APR unknown: never invent interest for this debt.
    aprBps: null,
    aprKind: "unknown",
    minPaymentCents: 5000,
    minPaymentIsEstimate: false,
    minPaymentDueDay: 15,
    source: DEMO,
    notes: "Interest terms unknown; payoff timing without interest is an estimate.",
  },
];

const goals: Goal[] = [
  {
    id: "goal-emergency",
    name: "Emergency fund",
    kind: "emergencyFund",
    targetCents: 1500000,
    // Matches the High-Yield Savings balance exactly.
    savedCents: 845000,
    priority: 1,
    source: DEMO,
  },
  {
    id: "goal-homerepair",
    name: "Home repair fund",
    kind: "custom",
    targetCents: 500000,
    savedCents: 125000,
    priority: 2,
    source: DEMO,
  },
];

/**
 * CONFIRMED goal contributions — dated, sourced, each pointing at the
 * transaction that is its evidence. There is exactly ONE in the demo because
 * there is exactly one savings transfer on record; nothing is invented to make
 * the history look fuller. The current goal balance comes from the account
 * record (goal.savedCents), not from this list.
 */
const goalContributions: GoalContribution[] = [
  {
    id: "gc-emergency-0902",
    goalId: "goal-emergency",
    amountCents: 20000,
    date: "2026-09-02",
    source: "userEntered",
    confirmed: true,
    note: "Matches the $200.00 transfer to High-Yield Savings on record (Sep 2, 2026).",
  },
];

const givingPlan: GivingPlan = {
  id: "giv-plan",
  // Fixed amount — NO preselected percentage anywhere in the demo.
  mode: "fixed",
  amountCents: 12000,
  percentBps: null,
  basis: "net",
  categories: ["charities", "mutualAid"],
  // Once per calendar month; per-check share resolves against the demo's pay
  // cadence (twice a month — 10th and 25th) via giving/perCheckShare, never a
  // hard-coded divide-by-two.
  frequency: "monthly",
  enabled: true,
  source: DEMO,
  notes: "Optional — the amount, timing, and priority are the user's choices.",
};

const automationRules: AutomationRule[] = [
  {
    id: "rule-emergency",
    name: "Transfer to emergency fund (draft)",
    sourceAccountId: "acc-checking",
    destinationAccountId: "acc-savings",
    amountType: "fixed",
    amountCents: 20000,
    percentBps: null,
    formula: null,
    maxCents: 40000,
    schedule: "perPaycheck",
    offsetDays: 1,
    status: "draft",
    simulated: true,
    authorizedAt: null,
    revokedAt: null,
    source: DEMO,
  },
  {
    id: "rule-cc-min",
    name: "Credit card minimum payment (draft)",
    sourceAccountId: "acc-checking",
    destinationAccountId: "acc-card",
    amountType: "formula",
    amountCents: null,
    percentBps: null,
    formula: "minimumPayment",
    maxCents: 9600,
    schedule: "onDueDate",
    offsetDays: 0,
    status: "draft",
    simulated: true,
    authorizedAt: null,
    revokedAt: null,
    linkedDebtId: "debt-card",
    source: DEMO,
  },
  {
    id: "rule-extra-debt",
    name: "Extra $150 to auto loan (draft)",
    sourceAccountId: "acc-checking",
    destinationAccountId: "acc-auto",
    amountType: "fixed",
    amountCents: 15000,
    percentBps: null,
    formula: null,
    maxCents: 15000,
    schedule: "perPaycheck",
    offsetDays: 2,
    status: "draft",
    simulated: true,
    authorizedAt: null,
    revokedAt: null,
    linkedDebtId: "debt-auto",
    source: DEMO,
  },
];

const transactions: Transaction[] = [
  // Checking — deposits.
  {
    id: "txn-payday-0826",
    accountId: "acc-checking",
    merchant: "Demo Manufacturer",
    amountCents: 215384,
    kind: "income",
    status: "posted",
    category: "income",
    transactedAt: "2026-08-26",
    postedAt: "2026-08-26",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  {
    id: "txn-payday-0910",
    accountId: "acc-checking",
    merchant: "Demo Manufacturer",
    amountCents: 215384,
    kind: "income",
    status: "posted",
    category: "income",
    transactedAt: "2026-09-10",
    postedAt: "2026-09-10",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  // Checking — bills.
  {
    id: "txn-rent-0901",
    accountId: "acc-checking",
    merchant: "Demo Apartments",
    amountCents: -165000,
    kind: "expense",
    status: "posted",
    category: "housing",
    transactedAt: "2026-09-01",
    postedAt: "2026-09-01",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  {
    id: "txn-electric-0812",
    accountId: "acc-checking",
    merchant: "Demo Utility Co.",
    amountCents: -9840,
    kind: "expense",
    status: "posted",
    category: "utilities",
    transactedAt: "2026-08-12",
    postedAt: "2026-08-12",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  {
    id: "txn-internet-0815",
    accountId: "acc-checking",
    merchant: "Demo Fiber",
    amountCents: -6999,
    kind: "expense",
    status: "posted",
    category: "utilities",
    transactedAt: "2026-08-15",
    postedAt: "2026-08-15",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  {
    id: "txn-cell-0908",
    accountId: "acc-checking",
    merchant: "Demo Wireless",
    amountCents: -11250,
    kind: "expense",
    status: "posted",
    category: "utilities",
    transactedAt: "2026-09-08",
    postedAt: "2026-09-08",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  {
    id: "txn-auto-ins-0817",
    accountId: "acc-checking",
    merchant: "Demo Mutual Insurance",
    amountCents: -11833,
    kind: "expense",
    status: "posted",
    category: "insurance",
    transactedAt: "2026-08-17",
    postedAt: "2026-08-17",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  {
    id: "txn-streaming-0811",
    accountId: "acc-checking",
    merchant: "Demo Stream",
    amountCents: -1599,
    kind: "expense",
    status: "posted",
    category: "subscription",
    transactedAt: "2026-08-11",
    postedAt: "2026-08-11",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  {
    id: "txn-music-0818",
    accountId: "acc-checking",
    merchant: "Demo Audio",
    amountCents: -1099,
    kind: "expense",
    status: "posted",
    category: "subscription",
    transactedAt: "2026-08-18",
    postedAt: "2026-08-18",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  {
    id: "txn-gym-0820",
    accountId: "acc-checking",
    merchant: "Demo Fitness",
    amountCents: -4500,
    kind: "expense",
    status: "posted",
    category: "subscription",
    transactedAt: "2026-08-20",
    postedAt: "2026-08-20",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  // Checking — card payment (a TRANSFER, never a spending event).
  {
    id: "txn-card-payment-0909",
    accountId: "acc-checking",
    merchant: "Payment to Platinum Rewards Card",
    amountCents: -50000,
    kind: "transfer",
    status: "posted",
    category: "transfers",
    transactedAt: "2026-09-09",
    postedAt: "2026-09-09",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  // Checking — transfer to savings (same money, counted once, as a transfer).
  {
    id: "txn-savings-xfer-0902",
    accountId: "acc-checking",
    merchant: "Transfer to High-Yield Savings",
    amountCents: -20000,
    kind: "transfer",
    status: "posted",
    category: "transfers",
    transactedAt: "2026-09-02",
    postedAt: "2026-09-02",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  // Checking — auto loan payment (one event; principal/interest is info only).
  {
    id: "txn-auto-payment-0905",
    accountId: "acc-checking",
    merchant: "Auto Loan Payment",
    amountCents: -31240,
    kind: "loanPayment",
    status: "posted",
    category: "auto loan",
    transactedAt: "2026-09-05",
    postedAt: "2026-09-05",
    splits: [],
    isExcluded: false,
    principalCents: 24506,
    interestCents: 6734,
    source: DEMO,
  },
  // Checking — pending purchase (already inside the available balance).
  {
    id: "txn-grocery-pending-0910",
    accountId: "acc-checking",
    merchant: "Corner Grocery",
    amountCents: -4217,
    kind: "expense",
    status: "pending",
    category: "groceries",
    transactedAt: "2026-09-10",
    postedAt: null,
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  // Savings — mirror of the checking→savings transfer.
  {
    id: "txn-savings-credit-0902",
    accountId: "acc-savings",
    merchant: "Transfer from Everyday Checking",
    amountCents: 20000,
    kind: "transfer",
    status: "posted",
    category: "transfers",
    transactedAt: "2026-09-02",
    postedAt: "2026-09-02",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  // Credit card — purchases, and the mirror of the card payment transfer.
  {
    id: "txn-card-groceries-0903",
    accountId: "acc-card",
    merchant: "Corner Grocery",
    amountCents: -8422,
    kind: "expense",
    status: "posted",
    category: "groceries",
    transactedAt: "2026-09-03",
    postedAt: "2026-09-04",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  {
    id: "txn-card-gas-0828",
    accountId: "acc-card",
    merchant: "Demo Fuel",
    amountCents: -4620,
    kind: "expense",
    status: "posted",
    category: "transport",
    transactedAt: "2026-08-28",
    postedAt: "2026-08-29",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  {
    id: "txn-card-dining-0906",
    accountId: "acc-card",
    merchant: "Lucca's Kitchen",
    amountCents: -6733,
    kind: "expense",
    status: "posted",
    category: "dining",
    transactedAt: "2026-09-06",
    postedAt: "2026-09-07",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
  {
    id: "txn-card-payment-credit-0909",
    accountId: "acc-card",
    merchant: "Payment from Everyday Checking",
    amountCents: 50000,
    kind: "transfer",
    status: "posted",
    category: "transfers",
    transactedAt: "2026-09-09",
    postedAt: "2026-09-09",
    splits: [],
    isExcluded: false,
    principalCents: null,
    interestCents: null,
    source: DEMO,
  },
];

/**
 * Build the demo snapshot. Deterministic: identical data on every call.
 * The result is deep-frozen; treat it as immutable.
 */
export function createDemoSnapshot(): DemoSnapshot {
  return deepFreeze({
    label: DEMO_LABEL,
    household: DEMO_HOUSEHOLD,
    version: DEMO_SNAPSHOT_VERSION,
    generatedAt: DEMO_GENERATED_AT,
    accounts,
    transactions,
    paychecks,
    obligations,
    debts,
    goals,
    givingPlan,
    goalContributions,
    automationRules,
  });
}